theme: jekyll-theme-slate
title: Xamron's homepage
description: My First Github Website
### SUMMARY

```
For the past 14 years, I’ve worked with several companies related to
the construction industry. I specialized in administrative tasks such
as preparation and submission of correspondences, transmittals,
submittals (materials, drawings, etc.), reports (daily, weekly, etc.),
maintaining register logs as well as data entry using Electronic
Document Management System (EDMS).
```
# NORMAN CALAYO

## Secretary / Document Controller

### CONTACT

### +971 56 1393973

```
mac.enzy3@gmail.com
```
```
Abu Dhabi, U.A.E.
```
### EDUCATION

```
AMA-CLC / Philippines
Network Tech. – 2005
Design & Programming - 2004
```
### MICROSOFT SKILLS
```
Outlook
Word
Excel
PPT
Power BI
```
### WORK EXPERIENCE

```
Company: China State Construction Engineering Corporation – M.E.
Duration: February 2020 – Present
Project: Etihad Rail Network – Civil Package – Stage 2A
Location: Ghweifat-Ruwais, Western Region, Abu Dhabi, U.A.E.
Client: Etihad Rail
```
```
Company: Ghantoot Transport & Gen. Cont. L.L.C. (Roads Division)
Duration: September 2019 – February 2020
Project: Residential Plots In Al Yeef-Liwa City
Location: Liwa, Western Region, Abu Dhabi, U.A.E.
Client: Abu Dhabi General Services (MUSANADA)
```
```
Company: Trans Emirates Electrical & Mechanical Works LLC
Duration: January 2016 – August 2019
Project 1: ADCO - BAB Infrastructure Expansion
Project 2: Residential Building – Khalifa City A
Project 3: Baniyas Cooperative Society - HQ
Location: Madinat Zayed / Khalifa A / Baniyas, Abu Dhabi, U.A.E.
```
```
Company: Mabani Delma General Contracting Co. LLC
Duration: March 2013 – January 2016
Project 1: Transmission System From Ghalilah to Rams
Project 2: Sewerage & Drainage for Al Quoz Industrial Area
Location: Ras Al Khaimah / Dubai U.A.E.
Client: FEWA (Federal Electricity and Water Authority)
```
```
Company: OSAN Group Of Companies (OSAN Properties)
Duration: November 2011 – February 2013
Project: ADNOC Camp Management / Shah Gas Project
Location: Hameem, Western Region, Abu Dhabi, U.A.E.
Client: ADNOC
```
```
Company: Mohammed Abdulmohsin Al-Kharafi & Sons (L.L.C.)
Duration: January 2009 – November 2011
Project: Salam Street
Location: Salam Street, Abu Dhabi, U.A.E.
Client: Abu Dhabi Government
```
```
Company: National Corporation for Tourism & Hotels
Duration: June 2007 – January 2009
Project: Abu Dhabi Marine Operating Company (ADMA-OPCO)
Location: Abu Dhabi, U.A.E.
```
### RESPONSIBILITIES

- Maintaining of Document Management System (EDMS)
- Preparation and Submission of
    Electronic Transmittals.
- Distribution of Register Log to
    concerned personnel
- Assisting the implementation of
    EDMS
- Responsible for the effective
    and efficient document control
    of all engineering documents
- Monitoring the document control
    requirements on a daily basis
- Collect / register all technical
    documents such as drawings
    and blueprints in the
    company’s system
- Print and distribute documents
    as needed
- Keep other personnel updated
    on new document versions and
    how to obtain access
- Handle records across various
    departments
- Maintain confidentiality
    regarding sensitive documents
- Create templates for use by other personnel
